/* generate test vector which is array of integers,
6 per conceptual record:
    0 ulong value
    1 int count
    2 uint rol32
    3 uint ror32
    4 ulong rol64
    5 ulong rot64
This could be an array of structs or 6 arrays, but
the initialization of all three choices is equally inefficient,
and the output of parallel arrays is more cumbersome, so leave it alone
for now.

Since 0 means success, and index of the first
failed entry is the error code, the first entry is skipped.
*/

#include <stdint.h>
#include <stdio.h>
#include <inttypes.h>
#include <stdlib.h>

#ifdef _MSC_VER
typedef unsigned __int64 UINT64;
#define I64 "I64"
#else
typedef long long UINT64;
#define I64 "ll"
#define _strtoui64 strtoull
#endif

#define ROTATE(type, name, direction, other_direction)          \
static type name(type value, int count)                         \
{                                                               \
    type const result = (value direction count) | (value other_direction (sizeof(type) * 8 - count));   \
    return result;                                              \
}

ROTATE(uint32_t, rol32, <<, >>)
ROTATE(uint32_t, ror32, >>, <<)
ROTATE(uint64_t, rol64, <<, >>)
ROTATE(uint64_t, ror64, >>, <<)

int counter;

static void print_number(int64_t value)
// Try a little bit for readability.
{
    if (value >= 0)
    {
        if (value <= 10)
        {
            printf("%-21" PRId64 ",", value);
            return;
        }
        printf("0x%-21" PRIX64 ",", value);
        return;
    }
    printf("%-21" PRId64 ",", value);
}

static void test(uint64_t value, int count)
{
    printf("/*%5d*/ ", ++counter);

    print_number(value);
    print_number(count);
    print_number(rol32((int)value, count));
    print_number(ror32((int)value, count));
    print_number(rol64(value, count));
    print_number(ror64(value, count));

    printf("\n");
}

int main(int argc, char** argv)
{
    printf("// This file is generated by monoext-gentestdata.c. Avoid hand editing it.\n"
           "public class MonoExtTestData\n"
           "{\n"
           "public static int k = 6;\n"
           "public static long[] data = {\n");

    printf("0,0,0,0,0,0, // skip first entry\n");

    for (int64_t value = -16; value <= 16; ++value)
    {
        // Print column headers every so often.
        printf("// %-5s %-21s %-21s %-21s %-21s %-21s %-21s\n",
               "index", "value", "count", "rol32", "ror32", "rol64", "ror64");
        for (int count = 0; count <= 16; ++count)
            test(value, count);
    }

    printf("};}");

    return 0;
}
