thisdir = class/Mono.Ext
SUBDIRS = 
include ../../build/rules.make

LIBRARY = Mono.Ext.dll
LIB_REFS = System.Core
KEYFILE = ../mono.pub
LIB_MCS_FLAGS = /unsafe

NO_TEST = yes

include ../../build/library.make

